title: DengYueMed
description: Global pharmaceutical supply & medical insights
remote_theme: just-the-docs/just-the-docs

header_pages:
  - oncology.md
  - rare-diseases.md
  - supply-chain.md
  - regulatory.md
  - about.md
  - contact.md
plugins:
  - jekyll-remote-theme
color_scheme: light

heading_anchors: true
logo: "/logo.png"
just_the_docs:
  custom_css:
    - custom
