title: DengYueMed
description: Global pharmaceutical supply & medical insights
remote_theme: just-the-docs/just-the-docs

header_pages:
  - about.md
  - contact.md
plugins:
  - jekyll-remote-theme
color_scheme: light

aux_links:
  "Visit GitHub":
    - "https://github.com/dengyuemed"
